#!/bin/zsh

typeset -gar PACKAGES=(
  "shell/common"
  "shell/bash"
  "shell/zsh"
  "pkg/vim"
  "pkg/tmux"
  "scripts"
)

typeset -ga USER_PACKAGES=( "${PACKAGES[@]}" )
typeset -ga FLAGS=()
typeset -g TARGET="${HOME}"

while getopts 'nDvt:v' flag; do
  case "${flag}" in
    n|D|v)
      FLAGS+=("-${flag}")
      ;;
    t)
      TARGET="${OPTARG}"
      if [ ! -d "$TARGET" ]; then
        echo "Target directory '$TARGET' does not exist"
        exit 1
      fi
      ;;
    *)
      echo "Usage: $0 [-n] [-d] [-v] [-t TARGET] [PKG...]"
      exit 1 ;;
  esac
done
shift $((OPTIND-1))

# Override packages by user arguments
if [ $# -gt 0 ]; then
  USER_PACKAGES=( "$@" )
fi

_install_pkg () {
  [[ $# -eq 0 ]] && return 1

  local _root="$(dirname "$1")"
  local _pkg="$(basename "$1")"

  typeset -a _params=(
    "${FLAGS[@]}"
    "-R"
    "-t ${TARGET}"
    "-d ${_root}"
    "${_pkg}"
  )
  echo "$ stow ${_params[@]}"
  stow ${_params[@]}
}

# Check for dependencies
deps=( "stow" "zsh" "tmux" )
mising=()
for dep in "${deps[@]}"; do
  if ! type "$dep" >&/dev/null; then
    missing+=("$dep")
  fi
done

if [ ${#missing[@]} -gt 0 ]; then
  echo "ERROR: Missing dependencies: ${missing[@]}"
  exit 2
fi

for pkg in "${PACKAGES[@]}"; do
  if [ ! -d "$pkg" ]; then
    echo "ERROR: Package '$pkg' does not exist"
    exit 2
  fi
  echo "Installing ${pkg}..."
  _install_pkg "${pkg}"
done
